const { chromium }=require('playwright');
(async()=>{let browser=await chromium.launch({headless:true,args:['--no-sandbox']}),page=await browser.newPage({viewport:{width:1512,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto('http://localhost:8080/#login');await page.getByLabel('Email address').fill('qa@example.test');await page.getByLabel('Password',{exact:true}).fill('qa-password-1234');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('heading',{name:/Good /}).waitFor();await page.screenshot({path:'qa-overview-desktop.png',fullPage:true});
await page.goto('http://localhost:8080/#edit?kind=code');await page.getByRole('heading',{name:'New code',exact:true}).waitFor();await page.getByLabel('Title',{exact:true}).fill('Browser tested algorithm');await page.locator('.CodeMirror').click();await page.keyboard.type('int main() { return 42; }');await page.locator('#save-status').filter({hasText:'All changes saved'}).waitFor();let savedUrl=page.url();if(!savedUrl.includes('id='))throw Error('Autosave did not create item');await page.screenshot({path:'qa-editor-desktop.png',fullPage:true});await page.goto(savedUrl);await page.locator('.CodeMirror').waitFor();if(!(await page.locator('.CodeMirror').textContent()).includes('return 42'))throw Error('Saved code missing');
await page.goto('http://localhost:8080/#edit?kind=note');await page.getByRole('heading',{name:'New note',exact:true}).waitFor();await page.getByLabel('Title',{exact:true}).fill('Lecture notes');await page.getByLabel('Note content').fill('# Chapter 1\nবাংলা নোট\n**Important** <script>alert(1)</script>');await page.locator('#save-status').filter({hasText:'All changes saved'}).waitFor();await page.getByRole('button',{name:'Preview',exact:true}).click();if(await page.locator('#note-preview script').count())throw Error('Unsafe preview');
for(let r of ['codes','notes','files','projects','tools','favorites','trash','notifications','settings','help','shared-with-me','admin']){await page.goto('http://localhost:8080/#'+r);await page.getByRole('heading',{name:({codes:'My Codes',notes:'Notes',files:'Files',projects:'Projects',tools:'Study Tools',favorites:'Favorites',trash:'Trash',notifications:'Notifications',settings:'Settings',help:'Help & Feedback','shared-with-me':'Shared With Me',admin:'Administration'})[r],exact:true}).waitFor();if((await page.locator('#main').textContent()).includes('Unable to open'))throw Error('Route failed '+r)}
await page.goto('http://localhost:8080/#tools');await page.getByRole('button',{name:/JSON Formatter/}).click();await page.getByLabel('Input',{exact:true}).fill('{"ok":true}');await page.getByRole('button',{name:'Format JSON',exact:true}).click();if(!(await page.locator('#tool-output').textContent()).includes('"ok": true'))throw Error('JSON formatter failed');
await page.setViewportSize({width:390,height:844});await page.goto('http://localhost:8080/#overview');await page.getByRole('heading',{name:/Good /}).waitFor();await page.screenshot({path:'qa-overview-mobile.png',fullPage:true});let over=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(over)throw Error('Mobile overflow');await page.getByRole('button',{name:'Open menu',exact:true}).click();await page.locator('dialog').getByRole('link',{name:'Settings',exact:true}).click();await page.getByRole('heading',{name:'Settings',exact:true}).waitFor();if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Settings mobile overflow');await page.screenshot({path:'qa-settings-mobile.png',fullPage:true});
await page.setViewportSize({width:1024,height:800});await page.goto('http://localhost:8080/#overview');await page.getByRole('heading',{name:/Good /}).waitFor();if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Tablet overflow');
await browser.close();if(errors.length)throw Error('Browser errors: '+errors.join('\n'));console.log('PASS: desktop/tablet/mobile routes, autosave persistence, Markdown escaping, JSON tool, mobile navigation, no horizontal overflow or browser errors.');})().catch(e=>{console.error(e);process.exit(1)});
