const {chromium}=require('playwright');
(async()=>{const b=await chromium.launch({args:['--no-sandbox']}),student=await b.newPage({viewport:{width:1512,height:1000}}),admin=await b.newPage(),errors=[];for(const p of[student,admin])p.on('pageerror',e=>errors.push(e.message));
async function login(p,email){await p.goto('http://localhost:8080/#login');await p.getByLabel('Email address',{exact:true}).fill(email);const pass=p.getByLabel('Password',{exact:true});await pass.fill(email.startsWith('visual')?'visual-password-1234':'qa-password-1234');await p.getByRole('button',{name:'Show password',exact:true}).click();if(await pass.getAttribute('type')!=='text')throw Error('Password reveal failed');await p.getByRole('button',{name:'Hide password',exact:true}).click();if(await pass.getAttribute('type')!=='password')throw Error('Password conceal failed');await p.getByRole('button',{name:'Sign in',exact:true}).click();await p.getByRole('heading',{name:/Good /}).waitFor()}
await login(student,'visual@example.test');await login(admin,'qa@example.test');await student.goto('http://localhost:8080/#notifications');await student.getByRole('heading',{name:'Notifications',exact:true}).first().waitFor();await student.locator('[data-mark-read]').click({force:true});await student.waitForTimeout(700);await student.locator('[data-mark-read]:disabled').waitFor();if(await student.locator('[data-mark-read]').evaluate(e=>getComputedStyle(e).cursor)!=='default')throw Error('Disabled cursor remains busy');await student.locator('[data-notification-filter=unread]').click();
await admin.goto('http://localhost:8080/#admin');const title='Live test '+Date.now();await admin.locator('#announce-form input').fill(title);await admin.locator('#announce-form textarea').fill('A central admin announcement delivered without reloading.');await admin.getByRole('button',{name:'Publish announcement',exact:true}).click();await student.locator('.notification-title h3').filter({hasText:title}).waitFor({timeout:10000});if(await student.locator('[data-notification-filter=unread]').getAttribute('aria-pressed')!=='true')throw Error('Filter lost on refresh');await student.locator('#header-notifications .unread-number:visible').waitFor();await student.screenshot({path:'BOU-CSE-Notes-v1.4.1-Notifications.png'});await student.locator('.notification-row').filter({hasText:title}).getByRole('button',{name:'Mark as read',exact:true}).click();await student.locator('.notification-row').filter({hasText:title}).waitFor({state:'hidden'});
// Verify central setting changes notify the student, and restore the original setting.
const original=await admin.evaluate(async()=>{const d=await(await fetch('api.php?action=admin_data')).json();return Object.fromEntries(d.settings.map(x=>[x.key,x.value]))});const updated={...original,quota_mb:Number(original.quota_mb)===500?501:500};
for(const settings of[updated,original]){await admin.evaluate(async(data)=>{const r=await fetch('api.php?action=admin_config',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':window.BOU.csrf},body:JSON.stringify(data)});if(!r.ok)throw Error(await r.text())},settings);await student.locator('.notification-title h3').filter({hasText:'Workspace settings updated'}).first().waitFor({timeout:10000});await student.locator('[data-mark-read]').click();await student.locator('[data-mark-read]:disabled').waitFor();}
await student.goto('http://localhost:8080/#settings');await student.getByRole('heading',{name:'Settings',exact:true}).waitFor();if(await student.locator('input[data-password-toggle]').count()!==4)throw Error('Missing settings toggles');await student.getByRole('button',{name:'Show password',exact:true}).first().click();await student.screenshot({path:'BOU-CSE-Notes-v1.4.1-Password-Controls.png'});await student.setViewportSize({width:390,height:844});if(await student.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
await student.goto('http://localhost:8080/#notifications');await student.locator('[data-mark-read]:disabled').waitFor();await student.context().setOffline(true);await student.waitForTimeout(3500);await student.context().setOffline(false);await student.locator('.notification-sync').filter({hasText:'Live updates'}).waitFor({timeout:10000});if(errors.length)throw Error(errors.join('\n'));console.log('PASS: password reveal/conceal, disabled cursor, live admin announcement, numbered badge, retained filter, individual read, settings toggles/mobile and reconnect.');await b.close()})().catch(e=>{console.error(e);process.exit(1)});
