const {chromium}=require('playwright');
(async()=>{const b=await chromium.launch({args:['--no-sandbox']}),p=await b.newPage({viewport:{width:1512,height:1100}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8080/#login');await p.getByLabel('Email address').fill('qa@example.test');await p.getByLabel('Password',{exact:true}).fill('qa-password-1234');await p.getByRole('button',{name:'Sign in',exact:true}).click();await p.getByRole('heading',{name:/Good /}).waitFor();
for(const [r,title] of [['courses','Courses'],['goals','Lab Goals'],['storage','Storage']]){await p.goto('http://localhost:8080/#'+r);await p.getByRole('heading',{name:title,exact:true}).waitFor()}
await p.goto('http://localhost:8080/#courses');await p.getByRole('button',{name:'Add Course',exact:true}).click();await p.locator('dialog').getByLabel('Title',{exact:true}).fill('Advance UI/UX & Algorithm Design');await p.getByLabel('Subject',{exact:true}).fill('Data Structures & Lab');await p.getByLabel('Course code').fill('CSE-212');await p.getByLabel('Total modules').fill('40');await p.getByLabel('Completed modules').fill('18');await p.getByLabel('Hours remaining').fill('2');await p.getByLabel('Course materials URL').fill('https://example.com/course');await p.getByRole('button',{name:'Save course',exact:true}).click();await p.locator('dialog').waitFor({state:'hidden'});await p.getByRole('link',{name:'Resume Advance UI/UX & Algorithm Design',exact:true}).last().click();await p.getByRole('heading',{name:'Advance UI/UX & Algorithm Design',exact:true}).first().waitFor();await p.getByRole('button',{name:'Update progress',exact:true}).click();await p.getByLabel('Completed modules').fill('40');await p.getByRole('button',{name:'Save course',exact:true}).click();await p.locator('dialog').waitFor({state:'hidden'});
await p.goto('http://localhost:8080/#goals');await p.getByRole('button',{name:'New Goal',exact:true}).click();await p.locator('dialog').getByLabel('Title',{exact:true}).fill('Complete Binary Search Lab');await p.getByRole('button',{name:'Save goal',exact:true}).click();await p.locator('dialog').waitFor({state:'hidden'});await p.getByRole('button',{name:'Complete goal',exact:true}).last().click();await p.getByRole('button',{name:'Mark incomplete',exact:true}).last().waitFor();
await p.goto('http://localhost:8080/#overview');await p.getByRole('heading',{name:/Good /}).waitFor();const oldWeek=await p.locator('#overview-streak').textContent();await p.locator('#overview-streak').getByRole('button',{name:'Previous week',exact:true}).click();if(await p.locator('#overview-streak').textContent()===oldWeek)throw Error('Week control inert');await p.locator('#overview-streak').getByRole('button',{name:'Next week',exact:true}).click();await p.locator('[data-language="SQL"]').click();await p.locator('[data-language="All"]').click();const gradient=await p.locator('#new-menu').evaluate(e=>getComputedStyle(e).backgroundImage);if(!gradient.includes('linear-gradient'))throw Error('Missing reference gradient');const sidebar=await p.locator('.reference-sidebar').boundingBox();if(sidebar.width!==250)throw Error('Desktop sidebar width differs');const bar=await p.locator('.reference-topbar').boundingBox();if(bar.height!==64)throw Error('Header differs');
await p.getByRole('button',{name:'Workspace pages',exact:true}).click();await p.locator('dialog').getByRole('link',{name:'Lab Goals',exact:true}).click();await p.getByRole('heading',{name:'Lab Goals',exact:true}).waitFor();
for(const w of [1512,1366,1280,1024,768,390]){await p.setViewportSize({width:w,height:1000});for(const route of ['overview','courses','goals','storage','codes','notes','files','projects','tools','shared-with-me','favorites','trash','notifications','settings','help','admin']){await p.goto('http://localhost:8080/#'+route);await p.locator('#main').waitFor();await p.waitForTimeout(100);if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Overflow '+route+' at '+w);if((await p.locator('#main').textContent()).includes('Unable to open'))throw Error('Failed '+route)}}
await b.close();if(errors.length)throw Error(errors.join('\n'));console.log('PASS: study CRUD/progress/goals, linked routes, week controls, language tabs, reference dimensions/gradients, all pages at 6 widths, no runtime errors.');})().catch(e=>{console.error(e);process.exit(1)});
