CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL,
 email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
 verified_at DATETIME NULL, role VARCHAR(20) NOT NULL DEFAULT 'student', status VARCHAR(20) NOT NULL DEFAULT 'active',
 semester VARCHAR(60) NOT NULL DEFAULT '', avatar VARCHAR(80) NOT NULL DEFAULT '',
 preferences TEXT NULL, session_version INT NOT NULL DEFAULT 1,
 created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL,
 kind VARCHAR(20) NOT NULL, title VARCHAR(255) NOT NULL, content MEDIUMTEXT NULL,
 description TEXT NULL, language VARCHAR(40) NOT NULL DEFAULT 'Plain Text', subject VARCHAR(120) NOT NULL DEFAULT '', tags TEXT NULL,
 project_id BIGINT UNSIGNED NULL, folder_id BIGINT UNSIGNED NULL,
 revision INT NOT NULL DEFAULT 1, favorite TINYINT NOT NULL DEFAULT 0, pinned TINYINT NOT NULL DEFAULT 0,
 stored_name VARCHAR(80) NULL, original_name VARCHAR(255) NULL, mime VARCHAR(120) NULL, size_bytes BIGINT NOT NULL DEFAULT 0,
 created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME NULL,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 INDEX items_owner_kind (user_id,kind,deleted_at), INDEX items_updated (user_id,updated_at),
 INDEX items_project (project_id), INDEX items_folder (folder_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS attachments (
 item_id BIGINT UNSIGNED NOT NULL, file_id BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(item_id,file_id), FOREIGN KEY(item_id) REFERENCES items(id) ON DELETE CASCADE,
 FOREIGN KEY(file_id) REFERENCES items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS versions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, item_id BIGINT UNSIGNED NOT NULL,
 content MEDIUMTEXT NOT NULL, created_at DATETIME NOT NULL,
 FOREIGN KEY(item_id) REFERENCES items(id) ON DELETE CASCADE, INDEX versions_item (item_id,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS tokens (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL,
 kind VARCHAR(20) NOT NULL, token_hash CHAR(64) NOT NULL UNIQUE, payload VARCHAR(190) NULL,
 expires_at DATETIME NOT NULL, created_at DATETIME NOT NULL,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS rate_limits (
 bucket CHAR(64) PRIMARY KEY, attempts INT NOT NULL DEFAULT 0, started_at BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS shares (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, item_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL, token_hash CHAR(64) NOT NULL UNIQUE,
 recipient_id BIGINT UNSIGNED NULL, expires_at DATETIME NULL, revoked_at DATETIME NULL, created_at DATETIME NOT NULL,
 FOREIGN KEY(item_id) REFERENCES items(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(recipient_id) REFERENCES users(id) ON DELETE CASCADE,
 INDEX shares_recipient (recipient_id,revoked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS notifications (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(255) NOT NULL, content TEXT NULL, read_at DATETIME NULL, created_at DATETIME NOT NULL,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX notify_owner (user_id,read_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS email_logs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, recipient VARCHAR(190) NOT NULL,
 kind VARCHAR(40) NOT NULL, status VARCHAR(20) NOT NULL, detail VARCHAR(255) NULL, created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS activity (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL,
 action VARCHAR(40) NOT NULL, created_at DATETIME NOT NULL,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX activity_owner (user_id,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS settings (`key` VARCHAR(80) PRIMARY KEY, value TEXT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO settings (`key`,value) VALUES ('quota_mb','500'),('max_upload_mb','10'),('trash_days','30'),('support_email','support@example.com');
